[ee_keys]
type = "service_account"
project_id = "ee-desmond"
private_key_id = "3f9d658216fbf51e3764ad7e1581a66eaa76ffc0"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOxDPaHDLJTVZT
EM37L9tYuWWUT3+3mg3dnOo98b19KJ+MFQOOzJbJdm8jBCNV2muWlO14hisaDgSs
v7x7VBcBwWI112jAqWQ2itX+HjRVdlPjTa5sq8QOMexWy8g6yWY8MYdkRk+jfCpl
RonyUnO0++BJjwTPL3dUOyaFJaQdJUJ2l2nzv4Sk7P+nDB0JMXiipPH/AlFi744Y
wla94XoCuakOZLgMr8oL77f2lhwKx7EzRfdqe65XFXHWDOzlo8HbHRB4ZmnwaD6i
xdKLvOXLGzd9h1xQ4SOX535dAgRdOgC8LbsbEz0kxtZpG2ZPCXqObiFSjXB5jQAB
cNqQidRnAgMBAAECggEAMZr6waogORFX04flkwzROAEKsME95+OKzg82V3QmvN9B
H89u0hSdXGoQkbsNayyCwVarfk3aC18vme5KHuB2wJIPqNEsLYS2KSu32UaP0a0Y
xSC+5w1ydOFfTReIyynEYE6Vp+YCdztzxGZe9Ab6AYKoNZ2dTsOZgljKjgkQzXjT
... (and so on) ...
-----END PRIVATE KEY-----
'''
client_email = "eedesmond@ee-desmond.iam.gserviceaccount.com"
client_id = "101390299790148102978"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/eedesmond%40ee-desmond.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
